#!/bin/sh
pip install dash 
pip install dash-core-components 
pip install dash-html-components 
pip install numpy 
pip install pandas 
pip install plotly 
pip install xlrd 
pip install Click 
pip install Flask 
pip install Flask-Compress 
pip install future 
pip install itsdangerous 
pip install Jinja2 
pip install MarkupSafe 
pip install python-dateutil 
pip install pytz 
pip install retrying 
pip install six 
pip install Werkzeug 
