#!/bin/sh
pip install pip --upgrade
pip install dash --upgrade
pip install dash-core-components --upgrade
pip install dash-html-components --upgrade
pip install numpy --upgrade
pip install pandas --upgrade
pip install plotly --upgrade
pip install xlrd --upgrade
pip install Click --upgrade
pip install Flask --upgrade
pip install Flask-Compress --upgrade
pip install future --upgrade
pip install itsdangerous --upgrade
pip install Jinja2 --upgrade
pip install MarkupSafe --upgrade
pip install python-dateutil --upgrade
pip install pytz --upgrade
pip install retrying --upgrade
pip install six --upgrade
pip install Werkzeug --upgrade
